version: "3.8"
services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    environment:
      - WG_HOST=wiregaurd.prithvirajchaudhuri.com
      - WG_PORT=51820
      - WG_ADMIN_LISTEN_PORT=51821
      - WG_DEFAULT_DNS=8.8.8.8,8.8.4.4
      - WG_MTU=1420
    volumes:
      - /home/ansible-user/wiregaurd/data:/etc/wireguard
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_lables=1
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wiregaurd.rule=Host(`wiregaurd.eq-01.pi.hole`)"
      - "traefik.http.routers.wiregaurd.entrypoints=websecure"
      - "traefik.http.routers.wiregaurd.service=wiregaurd"
      - "traefik.http.services.wiregaurd.loadbalancer.server.port=51821"

networks:
  traefik:
    external: true